create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create table if not exists public.tables (
  id uuid primary key default gen_random_uuid(),
  table_number text not null unique,
  name text,
  sort_order integer not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.guests (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  table_id uuid not null references public.tables(id) on update cascade on delete restrict,
  seat_number integer check (seat_number is null or seat_number > 0),
  group_name text,
  attendance_status text not null default 'pending' check (attendance_status in ('pending', 'arrived', 'absent')),
  arrival_time timestamptz,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (table_id, seat_number)
);

create index if not exists guests_name_search_idx on public.guests using gin (lower(name) gin_trgm_ops);
create index if not exists guests_group_name_idx on public.guests (group_name);
create index if not exists guests_table_id_idx on public.guests (table_id) where active;

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  guest_id uuid references public.guests(id) on delete set null,
  previous_value jsonb,
  new_value jsonb,
  timestamp timestamptz not null default now()
);

alter table public.tables enable row level security;
alter table public.guests enable row level security;
alter table public.activity_logs enable row level security;

create or replace function public.search_guest_records(p_query text)
returns table (id uuid, name text, table_id uuid, seat_number integer, group_name text, attendance_status text, arrival_time timestamptz, notes text, active boolean, table_number text)
language sql stable security definer set search_path = public as $$
  select g.id, g.name, g.table_id, g.seat_number, g.group_name, g.attendance_status, g.arrival_time, g.notes, g.active, t.table_number
  from public.guests g join public.tables t on t.id = g.table_id
  where g.active and (g.name ilike '%' || p_query || '%' or coalesce(g.group_name, '') ilike '%' || p_query || '%')
  order by coalesce(g.group_name, g.name), g.name, g.seat_number;
$$;

create or replace function public.check_in_guest(p_guest_id uuid)
returns table (id uuid, name text, table_id uuid, seat_number integer, group_name text, attendance_status text, arrival_time timestamptz, notes text, active boolean, table_number text)
language plpgsql security definer set search_path = public as $$
declare previous jsonb;
begin
  select to_jsonb(g) into previous from public.guests g where g.id = p_guest_id and g.active;
  if previous is null then raise exception 'Guest not found'; end if;
  update public.guests g set attendance_status = 'arrived', arrival_time = now(), updated_at = now() where g.id = p_guest_id;
  insert into public.activity_logs(action, guest_id, previous_value, new_value) select 'check_in', g.id, previous, to_jsonb(g) from public.guests g where g.id = p_guest_id;
  return query select g.id, g.name, g.table_id, g.seat_number, g.group_name, g.attendance_status, g.arrival_time, g.notes, g.active, t.table_number from public.guests g join public.tables t on t.id = g.table_id where g.id = p_guest_id;
end; $$;

create or replace function public.undo_guest_check_in(p_guest_id uuid)
returns table (id uuid, name text, table_id uuid, seat_number integer, group_name text, attendance_status text, arrival_time timestamptz, notes text, active boolean, table_number text)
language plpgsql security definer set search_path = public as $$
declare previous jsonb;
begin
  select to_jsonb(g) into previous from public.guests g where g.id = p_guest_id and g.active;
  if previous is null then raise exception 'Guest not found'; end if;
  update public.guests g set attendance_status = 'pending', arrival_time = null, updated_at = now() where g.id = p_guest_id;
  insert into public.activity_logs(action, guest_id, previous_value, new_value) select 'undo_check_in', g.id, previous, to_jsonb(g) from public.guests g where g.id = p_guest_id;
  return query select g.id, g.name, g.table_id, g.seat_number, g.group_name, g.attendance_status, g.arrival_time, g.notes, g.active, t.table_number from public.guests g join public.tables t on t.id = g.table_id where g.id = p_guest_id;
end; $$;

revoke all on function public.check_in_guest(uuid) from public, anon, authenticated;
revoke all on function public.undo_guest_check_in(uuid) from public, anon, authenticated;
revoke all on function public.search_guest_records(text) from public, anon, authenticated;
grant execute on function public.check_in_guest(uuid) to service_role;
grant execute on function public.undo_guest_check_in(uuid) to service_role;
grant execute on function public.search_guest_records(text) to service_role;

do $$ begin
  alter publication supabase_realtime add table public.guests;
exception when duplicate_object then null;
end $$;
