"use client";
import { Check, LoaderCircle, RotateCcw } from "lucide-react";
import type { Guest } from "@/lib/types";

export function GuestCard({ guest, busy, onCheckIn, onUndo }: { guest: Guest; busy?: boolean; onCheckIn: (guest: Guest) => void; onUndo: (guest: Guest) => void }) {
  const arrived = guest.attendance_status === "arrived";
  return <article className={`rounded-2xl border p-5 shadow-sm sm:p-6 ${arrived ? "border-[#D8C3A5] bg-[#D8C3A5]" : "border-[#D8C3A5] bg-white"}`}><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="mb-1 text-sm font-bold uppercase tracking-[.12em] text-[#8B6B4A]">{guest.group_name ?? "Guest"}</p><h2 className="truncate font-serif text-2xl font-semibold sm:text-3xl">{guest.name}</h2></div><span className={`shrink-0 rounded-full px-3 py-1.5 text-sm font-bold ${arrived ? "bg-[#D8C3A5] text-[#6B2C2C]" : "bg-[#D8C3A5] text-[#8B6B4A]"}`}>{arrived ? "Arrived" : "Not arrived"}</span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#D8C3A5] px-4 py-3"><span className="block text-sm font-semibold text-[#8B6B4A]">TABLE</span><strong className="text-3xl text-[#6B2C2C]">{guest.table_number}</strong></div><div className="rounded-xl bg-[#D8C3A5] px-4 py-3"><span className="block text-sm font-semibold text-[#8B6B4A]">SEAT</span><strong className="text-3xl text-[#6B2C2C]">{guest.seat_number ?? "—"}</strong></div></div>{!arrived && <button type="button" disabled={busy} onClick={() => onCheckIn(guest)} className="mt-5 flex min-h-16 w-full items-center justify-center gap-3 rounded-xl bg-[#6B2C2C] px-6 text-xl font-extrabold tracking-wide text-white shadow-sm transition hover:bg-[#6B2C2C] active:scale-[.99] disabled:opacity-60">{busy ? <LoaderCircle className="animate-spin" /> : <Check strokeWidth={3} />} CHECK IN</button>}{arrived && <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-base font-medium text-[#8B6B4A]">{guest.arrival_time ? `Checked in at ${new Date(guest.arrival_time).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}` : "Checked in"}</p><button type="button" disabled={busy} onClick={() => onUndo(guest)} className="flex min-h-12 items-center justify-center gap-2 rounded-xl border-2 border-[#8B6B4A] bg-white px-5 font-extrabold text-[#6B2C2C] transition hover:bg-[#D8C3A5] active:scale-[.99] disabled:opacity-60">{busy ? <LoaderCircle className="animate-spin" /> : <RotateCcw size={20} />} UNDO CHECK-IN</button></div>}</article>;
}


